#!/bin/bash
docker build -t workdesk .

if [ $? = 0 ] ; then
    echo -e "\n\nsuccess"
    echo -e "\n Use command \"alias workdesk='docker run --rm -v $(pwd):/tencc -w /tencc workdesk'\""
else
    echo -e "\n\nfailed"
fi
